FROM ubuntu:latest
#なんのイメージを使って作るかを指定

#RUNはコマンドを実行したいとき
EXPOSE 22 5963 5001
#EXPOSEはポート開く
#RUN ip a
#RUN which iperf3

RUN apt-get update
RUN apt-get install build-essential -y
RUN apt-get install wget -y
RUN apt-get install -y iputils-ping net-tools
RUN apt-get install -y iproute2 -y
RUN apt-get install -y iperf3
RUN apt-get install iptables -y
RUN apt-get install bridge-utils
RUN apt-get install traceroute
RUN ["apt-get", "install", "-y", "vim"]
RUN apt-get install systemctl -y
RUN apt-get install tcpdump -y
RUN apt install curl -y
RUN apt install ufw -y
RUN apt-get install dnsutils -y 

RUN wget https://sourceforge.net/projects/ion-dtn/files/ion-open-source-4.1.2.tar.gz/download
RUN tar xzvf download
WORKDIR /ion-open-source-4.1.2
RUN CFLAGS="-Wno-nonnull -Wno-enum-int-mismatch" ./configure
RUN make
RUN make install
RUN ldconfig
#RUN apt install build-essential libssl-dev openssl libdbi-perl -y
#RUN wget http://www.squid-cache.org/Versions/v5/squid-5.7.tar.gz
#RUN tar xzf squid-5.7.tar.gz
#WORKDIR /squid-5.7
#RUN ./configure --with-openssl --enable-ssl-crtd 
#RUN make
#RUN make install
#RUN /usr/local/squid/libexec/security_file_certgen -c -s /var/lib/ssl_db -M 4MB
